GROUP_ID=io.github.vafeen
ARTIFACT_MODULE_NAME=test-publish
VERSION=1.0.0
SOURCES_PACKAGE=ru.vafeen.testpublish
PROJECT_NAME=Test project
PROJECT_DESCRIPTION=Test project
PROJECT_URL=https://github.com/vafeen/testproject
SCM_URL=https://github.com/vafeen/testproject.git
DEVELOPER_NAME=A
DEVELOPER_EMAIL=666av6@gmail.com
ORGANIZATION=A
ORGANIZATION_URL=https://example.com
SOURCE_CODE_PATH := $(ARTIFACT_MODULE_NAME)/src/main/java