#!/bin/bash

export TOKEN=$(echo "$SONATYPE_USERNAME:$SONATYPE_PASSWORD" | base64)
export GPG_KEY_FILE="private_key.asc"
export PUBLISHER="bash2sonatype"

export BASE_DIR="$(pwd)"
export BUILD_DIR="$BASE_DIR/$PUBLISHER/build"
export ARTIFACT_PREFIX="$ARTIFACT_ID-$VERSION"

export PACKAGING_TYPE="jar"
if [[ "$ASSEMBLED_FILE" == *.aar ]]; then
    export PACKAGING_TYPE="aar"
    log_info "Определен тип упаковки: aar"
else
    log_info "Определен тип упаковки: jar"
fi

# Имена файлов
export FINAL_LIB_FILE="$BUILD_DIR/$ARTIFACT_PREFIX.$PACKAGING_TYPE"
export SOURCES_JAR="$BUILD_DIR/$ARTIFACT_PREFIX-sources.jar"
export JAVADOC_JAR="$BUILD_DIR/$ARTIFACT_PREFIX-javadoc.jar"
export POM_FILE="$BUILD_DIR/$ARTIFACT_PREFIX.pom"
export SETTINGS_FILE="$BUILD_DIR/settings.xml"

# Пути для bundle
export MAVEN_REPO_DIR="$BUILD_DIR/maven-repo"
export MAVEN_DIR="$MAVEN_REPO_DIR/$(echo $GROUP_ID | tr '.' '/')/$ARTIFACT_ID/$VERSION"

export BUNDLE_ZIP="$BUILD_DIR/$ARTIFACT_PREFIX.tar.gz"

export REPOSITORY_ID="ossrh"
export REPOSITORY_URL="https://central.sonatype.com/"

check_config() {
    echo "=== ПРОВЕРКА КОНФИГУРАЦИИ ==="
    echo "Base Dir: $BASE_DIR"
    echo "Group ID: $GROUP_ID"
    echo "Artifact/Module Name: $ARTIFACT_ID"
    echo "Version: $VERSION"
    echo "Final JAR: $(basename "$FINAL_LIB_FILE")"
    echo "Sources JAR: $(basename "$SOURCES_JAR")"
    echo "Javadoc JAR: $(basename "$JAVADOC_JAR")"
    echo "POM File: $(basename "$POM_FILE")"
    echo "Maven Dir: $MAVEN_DIR"
    echo "Target Dir: $BUILD_DIR"
    echo "Repository ID: $REPOSITORY_ID"
    echo "Repository URL: $REPOSITORY_URL"
    echo "Username set: $(if [ -z "$SONATYPE_USERNAME" ]; then echo "NO"; else echo "YES"; fi)"
    echo "Password set: $(if [ -z "$SONATYPE_PASSWORD" ]; then echo "NO"; else echo "YES"; fi)"
    echo "GPG Key ID: $GPG_KEY_ID"
    echo "GPG Passphrase set: $(if [ -z "$GPG_PASSPHRASE" ]; then echo "NO"; else echo "YES"; fi)"
    echo "=============================="
}